title: <p align="center"> Rifqi Azhari </p>

logo: "/images/picture.png?raw=true"

description:
  <p align="center">
  <a href="file/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/rifqiazhari/">LinkedIn</a> |
  <a href="https://github.com/rifqiazhari">GitHub</a> |
  <a href="https://www.kaggle.com/irahza">Kaggle</a> |
  <a href="https://medium.com/@rifqiazhari">Medium</a> |
  <a href="https://public.tableau.com/app/profile/rifqiazhari/vizzes">Tableau</a> |
  <a href="file/robotics_portfolio.pdf">Robotics_Portf</a> |
  <a href="https://academic.oup.com/ce/article/6/5/776/6786002">Publication</a> |
  <a href="file/certifications.pdf">DS/ML/DL Certifications</a>
  </p>
  <p align="justify">
  Engineering fresh graduate from Universitas Indonesia, 2x Project Manager in Flying Robotics Research Team for Int. Competition, 2x Teaching Assistant, 1x Research Assistant with Int. Publication. Had a 6-months internship in Diagnostic Analytics (Maintenance Engineer) in Oil & Gas.
  <br><be>
  </p>
  
theme: jekyll-theme-minimal
